### ISSUE TITLE
feeds.opml packaged in read-only location

### ISSUE THREAD

**Issue by pulkomandy** [pulkomandy/fRiSS#35]
Makes it tricky to setup friss initially. You need to run it once, then edit the preferences files to point to a writable feeds.opml, before you can edit the feeds list.

**Comment by Premislaus** [comment]
Can you change the default location of feeds.opml? Maybe-/boot/home/config/non-packaged/data/friss?

**Comment by Premislaus** [comment]
Can you change the default location of feeds.opml? Maybe-/boot/home/config/non-packaged/data/friss?
